// Date: 12/18/2013 11:14:06 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package zornco.reploidcraft.client.renderers;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelItemHolder extends ModelBase
{
	//fields
	ModelRenderer base;
	ModelRenderer beam1;
	ModelRenderer light2;
	ModelRenderer light1;
	ModelRenderer light3;
	ModelRenderer light4;
	ModelRenderer beam2;
	ModelRenderer beam3;
	ModelRenderer beam4;
	ModelRenderer Shape1;

	public ModelItemHolder()
	{
		textureWidth = 64;
		textureHeight = 32;

		base = new ModelRenderer(this, 0, 0);
		base.addBox(0F, 0F, 0F, 14, 1, 14);
		base.setRotationPoint(1F, -1F, 1F);
		base.setTextureSize(64, 32);
		setRotation(base, 0F, 0F, 0F);
		beam1 = new ModelRenderer(this, 0, 15);
		beam1.addBox(-8F, -1.5F, -0.5F, 7, 2, 1);
		beam1.setRotationPoint(13F, -1F, 3F);
		beam1.setTextureSize(64, 32);
		setRotation(beam1, 0F, 0.7853982F, 0.7853982F);
		light2 = new ModelRenderer(this, 0, 18);
		light2.addBox(-1F, -2F, -1F, 2, 3, 2);
		light2.setRotationPoint(13F, -1F, 13F);
		light2.setTextureSize(64, 32);
		setRotation(light2, 0F, -0.7853982F, 0.7853982F);
		light1 = new ModelRenderer(this, 0, 18);
		light1.addBox(-1F, -2F, -1F, 2, 3, 2);
		light1.setRotationPoint(13F, -1F, 3F);
		light1.setTextureSize(64, 32);
		setRotation(light1, 0F, 0.7853982F, 0.7853982F);
		light3 = new ModelRenderer(this, 0, 18);
		light3.addBox(-1F, -2F, -1F, 2, 3, 2);
		light3.setRotationPoint(3F, -1F, 3F);
		light3.setTextureSize(64, 32);
		setRotation(light3, 0F, 2.356194F, 0.7853982F);
		light4 = new ModelRenderer(this, 0, 18);
		light4.addBox(-1F, -2F, -1F, 2, 3, 2);
		light4.setRotationPoint(3F, -1F, 13F);
		light4.setTextureSize(64, 32);
		setRotation(light4, 0F, -2.356194F, 0.7853982F);
		beam2 = new ModelRenderer(this, 0, 15);
		beam2.addBox(-8F, -1.5F, -0.5F, 7, 2, 1);
		beam2.setRotationPoint(13F, -1F, 13F);
		beam2.setTextureSize(64, 32);
		setRotation(beam2, 0F, -0.7853982F, 0.7853982F);
		beam3 = new ModelRenderer(this, 0, 15);
		beam3.addBox(-8F, -1.5F, -0.5F, 7, 2, 1);
		beam3.setRotationPoint(3F, -1F, 3F);
		beam3.setTextureSize(64, 32);
		setRotation(beam3, 0F, 2.356194F, 0.7853982F);
		beam4 = new ModelRenderer(this, 0, 15);
		beam4.addBox(-8F, -1.5F, -0.5F, 7, 2, 1);
		beam4.setRotationPoint(3F, -1F, 13F);
		beam4.setTextureSize(64, 32);
		setRotation(beam4, 0F, -2.356194F, 0.7853982F);
		Shape1 = new ModelRenderer(this, 0, 23);
		Shape1.addBox(-1.5F, -1.5F, -1.5F, 3, 3, 3);
		Shape1.setRotationPoint(8F, -9F, 8F);
		Shape1.setTextureSize(64, 32);
		setRotation(Shape1, 0F, 0F, 0F);
	}

	public void render(float size, boolean empty)
	{
		base.render(size);
		light1.renderWithRotation(size);
		light2.renderWithRotation(size);
		light3.renderWithRotation(size);
		light4.renderWithRotation(size);
		if(empty)
			Shape1.render(size);
	}

	public void renderLight(float size)
	{
		beam1.renderWithRotation(size);
		beam2.renderWithRotation(size);
		beam3.renderWithRotation(size);
		beam4.renderWithRotation(size);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

}
